### ISSUE TITLE
Add memcached to environment setup script?

### ISSUE THREAD

**Issue by wxactly** [thinkshout/ts_recipes#4]
```
brew install memcached
ln -sfv /usr/local/opt/memcached/*.plist ~/Library/LaunchAgents
launchctl load ~/Library/LaunchAgents/homebrew.mxcl.memcached.plist
brew install php55-memcached
```

**Comment by unclegcb** [comment]
I'm using php56, should we install 2 versions?

**Comment by wxactly** [comment]
Ideally we'd use the latest version of php, or standardize on a set of versions, yeah. Currently the environment setup script only installs php55 to maintain parity with pantheon. If you're running php56, that would've been all configured by you.
